

# Documentation and Making-of: Revised versions of Redesign and Deceptive data products  

Neville Fernandes

## Problem Statement  
The topic of gun violence is quite polarizing and the debate around it, intense for almost any person in the United States. A big reason why this is the case is because violence perpetrated with guns has many different causes, but the consequences are the same for the victims, perpetrators, community, industry and the psyche of the nation as a whole. There are a lot of variables involved in the process of buying guns, gun-related violence and outcomes in curbing that with gun control. All of this, combined with the attitudes among the pro-gun owndership towards guns and what it means within the realm of citizen rights, makes it very difficult to analyze the various gun-related statistics out there and arrive at a single, overarching conclusion.  

Research on gun-related topics is hard to come by, and performing gun control research in particular is legislatively incentivised against. I had previously summarized some of the literature on the topic in my [earlier problem statement](https://github.com/neophyticfern/Data-Viz-Individual-Project). The important points to note are - 
* The 1996 Dickey Amendment passed by Congress and 2011 restriction on NIH effectively witholding funds on gun control research from the CDC and NIH (H.R. 3610, 1997) (H.R. 2055, 2012)
* Reduced gun availability is correlated with reduced number of gun suicides and mass shootings (Leigh & Neill, 2010) (Rodríguez Andrés & Hempstead, 2011)
* Nevetheless, people desire guns and procure them for self-defense, among other things (Kleck & Gertz, 1995)  

The 17-chart article by Vox on gun violence in America attempts to convince the audience that tighter gun control laws and reduced gun ownership can lead to reduced homicides, suicides and mass shootings and that there seems to be a slight majority in favor of some gun control policies in America (Lopez, 2018)). Obviously, the article is geared towards a readership that is educated, left-leaning and pro-gun control, the assumption of which leads to oversight and confirmation bias on the part of both the creator and consumer of these visuals. But it has a number of technical flaws as well - charts that could be better designed to drive home the point better, lack of consistency across all visuals, confusing use of color and space (data-pixel ratio) and stretching the accuracy of claims. I also felt that the large number of visuals lenghtens the article adversely by making it more difficult to assimilate the information cohesively. 

I picked visuals #1 & #2 (combined), #8 and #10 from the article for the redesign data product, and #1 & #6 (combined), #2 & #6 (combined) and #13 for the deceptive data product. My goal was to adjust the data-pizel ratio, reduce undue use of color and make it to drive home specific points, repurpose the evidence from the source and adhere to the argumentation model. I have also combined some of the charts in both of data products to save the audience the time and attention to assimilate the message, as I felt that the points that the original charts were trying to make were similar.

## Redesign data product  

I have created three different visuals in Tableau which display interesting, non-trivial, and somewhat unexpected findings. All three visuals are charts created using Tableau, labeled as [Redesign - Revised version](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Redesign-Revisedversion/Story1). The three visuals from the original version are available [here](https://public.tableau.com/profile/neville.fernandes#!/) labeled as [Vox individual project - Insight 1-a](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Voxindividualproject-Insight1-a/Story1), [Insight 1-b](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Gunownership-deaths/Story2), [Insight 2](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Voxindividualproject-Insight2/Story1) and [Insight 3](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Voxindividualproject-Insight3/Story1) respectively. The making of the three visuals is detailed below.  

### 1. Comparison of gun deaths between US and rest of the world  

This is a redesign of chart #1 and #2. The data for this visual was taken from [this spreadsheet](https://docs.google.com/spreadsheets/d/1chqUZHuY6cXYrRYkuE0uwXisGaYvr7durZHJhpLGycs/) created by Simon Rogers of the Guardian (Rogers, 2012). The first version created two charts: the first juxtaposes the rate of firearm ownership with the rate of firearm homicides, between USA and other select OECD countries (plus Argentina & Uruguay), whereas the second juxtaposes the rank of firearm ownership with firearm homicides for USA and other countries with high gun deaths. The attempt here was to showcase that the original Vox charts can easily be manipulated to convey a different message - that USA doesn't have as many deaths, if compared with some other countries in the OECD bracket and that having most of the guns in the world doesn't mean cannot necessarily be correlated with having more gun deaths.

The initial version has two charts, created by using the 'World firearms murders and ownership'. THe first one is a bar chart with _Country/Territory_ as the column and _Average firearms per 100 people_ and _Homicide by firearms rate per 100,000 population_ as the rows, color-coded and filters applied: _Country/Territory_ to select certain OECD countries and _Homicide by firearms rate per 100,000 population_ limited to 38.97. The second one is also a bar chart, this time with _Homicide by firearms rate per 100,000 population_ and _Rank by rate of ownership_ as the rows and similar filters were applied, the difference being that _Homicide by firearms rate per 100,000 population_ was limited to 68.43.  

In the redesigned version, the first chart was combined into one ('Dual axis merge') and the list of countries was kept the same as in Vox's version. 

### 2. Effect of gun control on gun deaths  
This is a redesign of visual #8 in the Vox article - States with tighter gun control laws have fewer gun-related deaths. The data for this visual was taken from [here](https://www.kff.org/other/state-indicator/firearms-death-rate-per-100000/?currentTimeframe=0&sortModel=%7B"colId":"Location","sort":"asc"%7D).  

The initial version is a map chart, created by generating the _Longitude_ and _Latitude_ variables and plotting _Longitude_ twice in the 'Columns' (Dual Axis applied) with _Latitude_ as a 'Row'. The _State_ dimension was added to both _Latitude_ and _Longitude_ marks. I then added _Firearms death rate per 100,000_ to the first _Longitude_ mark and _Gun measure law per state_ to the second _Longitude_ mark. The two measures were color-coded, the first measure in grey, the second in gold-dark pink. The attempt was to simplify the original map by removing the extra colors that take away from the central argument - that states with at least 1 gun control laws protecting children have lower rates of firearm deaths (Argumentation model, use of colors, data-pixel ratio).  

The redesign attemped to sharpen this visual and its central argument. To do this, I changed the chart from a map, which while being pretty can be difficult to interpret, to a simple bar chart. I created two plots, with _Firearms death rate per 100,000_ as the 'Row' in both cases, and set the filter to include only states from one category (0 laws and at least 1 law) at a time. Placed side by side, it can be easily seen that the states with zero laws protcting children have a higher rate than those with at least 1 law.  

### 3. Suicides make up gun deaths more than homicides do
This is a redesign of visual #10 - Most gun deaths are suicides. The data for this was sourced from the [CDC website](https://webappa.cdc.gov/sasweb/ncipc/mortrate10_us.html).

The initial version was created from two separate data files 'Total - Firearm' and 'Suicide - Firearm'. I merged the two files in Tableau on the common variable _Year_ from both dataframes. The chart was created by taking _Year_ dimension as a column and _Deaths_ measures from both dataframe as rows, then performing a 'Dual Axis' merging of the two measures. _Measure names_ dimension was added to the 'Marks' to color-code the two trends.  

In the redesigned version, the data used was a single dataframe created by merging the two earlier files with the 'Homicides - Firearm' file (simple merge operation on _Year_ variable performed in R). The chart was created by taking _Year_ dimension as a column and _Deaths_ measures _Cause of Death_ dimension was added to the 'Marks' to simultaneously idetify and color-code the three trends.  

The redesinged version improved on this chart, by also show the trend for deaths resulting from homicides as well. This showed that the firearm suicides have always been more that firearm homicides and that the increase in firearm suicides is what contributes to the increase in total firearm deaths. Thus, it clarifies the original argument and strengthens it at the same time, by sticking striclty to Toulmin's argumentation model, providing more evidence and showing clear use of metrics to answer the question.  

  
## Deceptive data product  

I have created three different visuals in Tableau which display interesting, non-trivial, and somewhat unexpected findings. All three visuals are charts created using Tableau, labeled as [Redesign - Deceptive version](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Redesign-Deceptiveversion/Story2) (excuse the confusing label - I intended to label it as 'Revised - Deceptive version'). The three visuals from the original version are available [here](https://public.tableau.com/profile/neville.fernandes#!/) labeled as [Ind. project - Deceptive data product 1](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Ind_Project-Deceptivedataproduct-1/Story1), [2](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Ind_Project-Deceptivedataproduct-2/Story2) and [3](https://public.tableau.com/profile/neville.fernandes#!/vizhome/Ind_Project-Deceptivedataproduct-3/Story3) respectively. The making of the three visuals is detailed below.  

### 1. More guns result in fewer deaths from guns  

The data for this chart was sourced from an article from the Guardian on gun homicides and gun ownership across the world (Chalabi, 2012). The link to the data is [here](https://docs.google.com/spreadsheets/d/1chqUZHuY6cXYrRYkuE0uwXisGaYvr7durZHJhpLGycs/edit#gid=0). Here we plotted the _Homicides by firearm rate (per 100,000 people)_ with the _Average firearms rate (per 100 people)_ and added a trendline to show how the homicide rate is correlated to the rate of firearm ownership. The Average firearms rate was added to the 'Column' field and Homicides by firearm rate was added to the 'Row' field (SUM was applied to both measures). The countries were selected based on a certain high-level of income, but intentionally so as to tilt the reference line to show a negative correlation between homicide rate and firearms rate. Additionally, the United States data point was annotated as well, to show the location with respect to the trend line and the rest of the data.  

In the revised version, we attempted to sharpen the chart by changing the data points from circles into solid circles. Additionally, we highlighted the extreme countries - Brazil and USA to bring attention to these two cases of low gun ownership-high crime rate and vice-versa. We also labeled some countries selectively to drive home the point that firearm homicide rates are in the same range for the fellow OECD countries as that for USA. The extreme cases of Brazil, South Africa and the Bahamas further puts the OECD countries in the same range.  

### 2. Responsible gun ownership in America  
The data for this chart was sourced from the same source as above (Chalabi, 2012). Three new fields were calculated from the original data - % of total guns in the world, % of total firearm homicides in the world and ratio of gun deaths to number of firearms. The details of the calculations are given below -  

	% of total guns in the world = [Average total all civilian firearms] * 100 / 644,008,400
		where 644,008,400 is the total number of guns in the world
	% of total firearm homicides in the world = [Number of homicides by firearm] * 100 / 127,607
	where 127,607 is the total number of firearm homicides in the world
	Ratio of gun deaths to number of firearms = [Homicide by firearm rate] / [Average firearms]
		where the ratio is per 1000 people.
  
The visual is actually two charts, placed one over the other. The 'Column' field in both charts is the Country dimension. The first chart shows a list of countries on the x-axis and % of total firearm homicides in the world and % of total guns in the world on the left and right y-axes respectively. Both of these measures were inputed into the 'Row' fields and then the Dual Axis option was applied to the latter. For the bottom chart, I used the third measure as calculated above in the 'Row' field. These charts were juxtaposed so that the countries were arranged in descending order of total firearm homicides in the world.  

The redesigned version attempts to improve upon the first version by trying to highlight the main countries and by the frugal use of color. Instead of having the countries as labels on the X-axis, I labeled the data points individually but selectively, making it easier to identify them. This is important as the first version did not have USA identified, making it difficult to identify it as having a low ratio of gun deaths/number of guns. I also did away with the color legend, and colored the data points with the same color as that of the measures on the Y-axis to more easily identify the data points while maintaining the data-pixel ratio. All of these changes make it easier to identify USA as the country with the lowest deaths/guns ratio, in spite of having a relatively higher number of total number of gun deaths.

### 3. Fewer guns doesn't lead to fewer homicides in Australia  
The data was sourced from the website of the Australian Bureau of Statistics, which covers the various causes of death in Australia (Australian Bureau of Statistics, 2017). The file downloaded is an Excel file attached for Intentional self-harm (Suicide). We used the data from sheet _Table 11.5_, which had the list for deaths by suicide for the year range of 2007-2016, from which the data for All Persons was manually transposed into a CSV file. Thus, we obtained the various categories of suicide as our measures (attributes) and the years as dimensions for our chart. From here, the measure of Firearms and Total were used in the 'Row' field in Tableau and the years were used as the dimension in the 'Column' field. The two measures were then combined in a Dual Axis. 
The caption covers a fact on rise in gun ownership, which was taken from the website GunPolicy.org (Alpers & Rosetti, 2018).  

In the redesigned version, we attempt to expand the evidence taken to generate the plot by adding in more information that was previously missing. We added data from the years 1997-2006 to the original chart. This makes our central argument more robust, by protecting it against a rebuttal, while still opposing the argument of the original Vox chart. The drop in total suicides in the middle can thought of as resulting from the decreased ownership from gun buyback, but the number of gun suicides remaining the same rebuts that idea. Also, another set of handguns was outlawed in 2003, but it showed no effect on the number of gun suicides in the years after that. 

## References  

Alpers, Philip, & Rosetti, Amelie. (2018). _Guns in Australia: Firearm Imports (Number)._ Sydney School of Public Health, The University of Sydney. Accessed 12 June 2018 at [GunPolicy.org](http://www.gunpolicy.org/firearms/compareyears/10/firearm_imports_number)  
Australian Bureau of Statistics. (2017). _Causes of Death, Australia, 2016._ Canberra, Australia. Retrieved from the [Australian Bureau of Statistics](http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/3303.02016?OpenDocument).  
Chalabi, Mona. (2012). _Gun homicides and gun ownership listed by country._ Accessed 12 June 2018 at [The Guardian](https://www.theguardian.com/news/datablog/2012/jul/22/gun-homicides-ownership-world-list).  
Lopez, German. (2018). _America's unique gun violence problem, explained in 17 maps and charts._ Accessed 12 June 2018 at [Vox](https://www.vox.com/policy-and-politics/2017/10/2/16399418/us-gun-violence-statistics-maps-charts).  
https://www.sciencemag.org/news/2017/09/nih-quietly-shelves-gun-research-program. (2017, September). Retrieved from Science.  
Kleck, G., & Gertz, M. (1995). Armed Resistance to Crime: The Prevalence and Nature of Self-Defense with a Gun. Journal of Criminal Law and Criminology, 86(1), 150-187.  
Leigh, A., & Neill, C. (2010). Do Gun Buybacks Save Lives? Evidence from Panel Data. American Law and Economics Review, 12(2), 509-557.  
Rodríguez Andrés, A., & Hempstead, K. (2011). Gun control and suicide: The impact of state firearm regulations in the United States, 1995–2004. Health Policy, 101(1), 95-103.  
Stark, D. E., & Shah, N. H. (2017). Funding and Publication of Research on Gun Violence and Other Leading Causes of Death. Journal of the American Medical Association, 917(1), 84-85.  
www.facebook.com/Vox/posts/617292708458335. (2016).  
